window.DEFAULT_PORTFOLIO = {
  defaultLanguage: "en",
  name: "Joffrey Achard",
  initials: "JA",
  eyebrow: "Bienvenue sur mon portfolio",
  headline: "Hi, I'm Joffrey! Explore my portfolio and the projects behind my journey.",
  intro:
    "Je m'appelle Joffrey Achard et je travaille dans le marketing digital et la communication.\n\nAprès plusieurs expériences en France, un semestre d'études au Royaume-Uni et plusieurs mois de voyage et de volontariat à travers l'Amérique du Nord et l'Amérique du Sud, j'ai développé une forte envie d'évoluer dans un environnement international.\n\nCe qui m'intéresse avant tout, c'est découvrir de nouvelles façons de travailler, collaborer avec des équipes multiculturelles et relever des défis dans des contextes différents. Le marketing est pour moi un moyen de créer du lien, raconter des histoires et faire rayonner des projets, quel que soit le pays où ils prennent vie.\n\nÀ travers ce portfolio, je partage mon parcours, mes réalisations et les expériences qui ont contribué à construire ma vision du monde et de mon métier.",
  profileTitle: "Un esprit curieux, tourné vers le monde.",
  profileText:
    "J'aime découvrir de nouveaux environnements, comprendre différentes façons de penser et sortir régulièrement de ma zone de confort. Une partie de moi a envie d'explorer, d'essayer et d'imaginer la suite. L'autre a besoin de construire, d'organiser et d'aller au bout des choses. Aujourd'hui, je cherche avant tout des projets qui me permettent d'apprendre, de collaborer avec des personnes venues d'horizons différents et de continuer à grandir, professionnellement comme personnellement.",
  videoTitle: "Ma vidéo de présentation",
  videoUrl: "assets/presentation.mp4",
  videoPoster: "assets/video-poster.svg",
  videoNoteTitle: "Un pitch direct",
  videoNote:
    "La vidéo sera disponible ici dès que le montage sera prêt. Elle servira à transmettre rapidement mon énergie, mon parcours et ma manière de travailler.",
  cvTitle: "CV et compétences",
  cvText:
    "Un parcours Bac+5, des expériences en marketing, une ouverture internationale et une pratique concrète de la communication digitale.",
  cvUrl: "assets/Resume_Joffrey_ACHARD.pdf",
  portfolioUrl: "assets/portfolio-joffrey-achard.pdf",
  detailedContent: {
    heroImage: "assets/photo_joffrey.jpeg",
    tefalHeaderImage: "assets/tefal-project-header.jpg",
    tefalPdf: "assets/Dossier-Tefal-Groupe-21.pdf",
    tefalTitleEn: "Leading an agency team for Tefal",
    tefalTitleFr: "Piloter une équipe en compétition d'agence pour Tefal",
    tefalProjectEn:
      "During my studies, I took part in several agency competitions. For the Tefal challenge, I acted as project manager: I led the team, organised our work, managed deadlines and guided the development of our ideas to build a coherent strategic and creative recommendation. We reached the final and finished second out of around twenty teams.",
    tefalProjectFr:
      "Pendant mes études, j'ai participé à plusieurs compétitions d'agences. Pour le challenge Tefal, j'occupais le rôle de chef de projet : j'ai managé l'équipe, organisé notre travail, piloté les délais et accompagné le développement de nos idées afin de construire une recommandation stratégique et créative cohérente. Nous avons atteint la finale et terminé deuxièmes parmi une vingtaine d'équipes.",
    tefalResultValue: "Top 2",
    tefalResultEn: "finalist among around twenty teams",
    tefalResultFr: "finaliste parmi une vingtaine d'équipes",
    videosCoverImage: "assets/videos-project-cover.jpg",
    videosBassettiEn:
      "To generate engagement on social media and enhance BASSETTI Group's brand image, I produced numerous motion design videos, handling the entire process, from creating the brief to final distribution, using Adobe Illustrator, After Effects and Premiere Pro.",
    videosBassettiFr:
      "Afin de générer de l'engagement sur les réseaux sociaux et de renforcer l'image de marque de BASSETTI Group, j'ai produit de nombreuses vidéos en motion design en prenant en charge l'ensemble du processus, de la création du brief jusqu'à la diffusion finale, avec Adobe Illustrator, After Effects et Premiere Pro.",
    videosEducleverEn:
      "I also created videos for Educlever, this time to promote an online dictation event for companies. I produced a report on the event, capturing key moments, selecting shots, adding effects, and managing its online distribution and promotion.",
    videosEducleverFr:
      "J'ai également créé des vidéos pour Educlever afin de promouvoir un événement de dictée en ligne destiné aux entreprises. J'ai réalisé un reportage sur l'événement en capturant les moments clés, en sélectionnant les plans, en ajoutant des effets et en assurant sa diffusion ainsi que sa promotion en ligne.",
    videoLinks: [
      "https://www.youtube.com/watch?v=ReREZda2Wp8&t=4s",
      "https://www.youtube.com/watch?v=6Ln2JXX_pzk",
      "https://www.youtube.com/watch?v=C3K3Ug_kClc",
      "https://www.youtube.com/watch?v=zlUU52Y0nnU",
      "https://www.youtube.com/watch?v=pWvoHdWWLek",
    ],
    videoImages: [
      "assets/video-bassetti-1.jpg",
      "assets/video-bassetti-2.jpg",
      "assets/video-bassetti-3.jpg",
      "assets/video-bassetti-4.jpg",
      "assets/video-educlever-report.jpg",
    ],
    videoTitlesEn: [
      "Event report",
      "Event announcement",
      "Interview",
      "Motion design",
      "New Year greeting card",
    ],
    videoTitlesFr: [
      "Reportage événement",
      "Annonce événement",
      "Interview",
      "Motion design",
      "Carte de vœux",
    ],
    briefProjectEn:
      "These motion design videos aim to promote the Agora Portal / Le Coin Infos (Project 1) on social media. As part of this project, I created the briefs, captured video content from the website, and organised the video structure to assist the motion design project manager in producing the videos.",
    briefProjectFr:
      "Ces vidéos en motion design ont pour objectif de promouvoir le Portail Agora / Le Coin Infos (Projet 1) sur les réseaux sociaux. Dans le cadre de ce projet, j'ai créé les briefs, capturé des contenus vidéo du site web et organisé la structure des vidéos afin d'accompagner le chef de projet motion design dans leur production.",
    briefVideoLink:
      "https://www.youtube.com/watch?v=8AQAjC1kFic&list=PLaxJVgkhTIUxC_CiFGCUwFuZlrdWHYQ6K",
    briefVideoImage: "assets/agora-motion-design-video.jpg",
    briefPdf: "assets/brief-motion-design-agora-aesio.pdf",
    briefHeaderImage: "assets/brief-project-header.jpg",
    chamrousseBefore: "assets/chamrousse-before.png",
    chamrousseAfter: "assets/chamrousse-after.png",
    whitePaperPdf: "assets/livre-blanc-festivals.pdf",
    whitePaperHeaderImage: "assets/white-paper-header.jpg",
    journalismEn:
      "Since August 2021, I have been working as a volunteer journalist for Valliue. I write and format articles for the website, which I then promote across our social media platforms (Instagram, Facebook and Twitter/X). Throughout the year, I also negotiate partnerships with organisations across France to promote their festivals, concerts or club events. These partnerships include the writing of several articles.",
    journalismFr:
      "Depuis août 2021, je travaille comme journaliste bénévole pour Valliue. Je rédige et mets en page des articles pour le site, que je valorise ensuite sur nos réseaux sociaux (Instagram, Facebook et Twitter/X). Tout au long de l'année, je négocie également des partenariats avec différentes organisations en France afin de promouvoir leurs festivals, concerts ou soirées en club. Ces partenariats comprennent la rédaction de plusieurs articles.",
    journalismLink: "https://valliue.com/author/jooffrey/",
    journalismArticleImage: "assets/valliue-article-preview.jpg",
    journalismCtaEn: "Discover all my articles",
    journalismCtaFr: "Découvrir tous mes articles",
    journalismArticlesValue: "70",
    journalismArticlesEn: "articles published",
    journalismArticlesFr: "articles publiés",
    journalismTrafficValue: "35%",
    journalismTrafficEn: "of Valliue's total website traffic generated in 2024 and 2025",
    journalismTrafficFr: "du trafic total du site Valliue généré en 2024 et 2025",
    journalismPartnersValue: "11",
    journalismPartnersEn: "new partners acquired",
    journalismPartnersFr: "nouveaux partenaires acquis",
    journalismPartners: [
      "Lollapalooza Paris",
      "Delta Festival",
      "Sea You Festival",
      "Dream Nation Festival",
      "Pharaonic Festival",
      "Dystopia Festival",
      "Audiogenic",
      "FCKNYE Festival",
      "Siks",
      "Stereoparc Festival",
      "Electrolapse Festival",
    ],
    documentsEn:
      "During my experience at BASSETTI Group, I created and updated various communication materials. I also developed support documents for the sales department at Educlever to promote the Orthodidacte product and showcase it during trade shows, business presentations, webinars and more.",
    documentsFr:
      "Lors de mon expérience chez BASSETTI Group, j'ai créé et mis à jour différents supports de communication. J'ai également conçu des documents pour l'équipe commerciale d'Educlever afin de promouvoir le produit Orthodidacte et de le présenter lors de salons, de présentations commerciales, de webinaires et d'autres événements.",
    documentsImage: "assets/documents-showcase.jpg",
    communicationPlanEn:
      "During my experience at Educlever as a Junior Marketing Promotion Officer, I developed several communication plans to strengthen Orthodidacte's brand awareness and promote the company within the spelling and French language market on LinkedIn. I designed the strategy, editorial planning and visuals, and managed the publications. On the left is an example from the L'Ortho Hebdo carousel series, which highlights statistics about the French language and presents the Orthodidacte solution.",
    communicationPlanFr:
      "Lors de mon expérience chez Educlever en tant que Junior Marketing Promotion Officer, j'ai élaboré plusieurs plans de communication afin de renforcer la notoriété d'Orthodidacte et de positionner l'entreprise sur le marché de l'orthographe et de la langue française sur LinkedIn. J'ai conçu la stratégie, le planning éditorial et les visuels, puis géré les publications. L'Ortho Hebdo est une série de carrousels qui met en avant des statistiques sur la langue française et présente la solution Orthodidacte.",
    communicationPlanImage: "assets/communication-plan-showcase.jpg",
    communicationPlanTrafficValue: "> 100%",
    communicationPlanTrafficEn: "traffic to the LinkedIn page",
    communicationPlanTrafficFr: "de trafic vers la page LinkedIn",
    newslettersEn:
      "As part of my communication strategy at Educlever, I designed and managed several newsletters aimed at strengthening the visibility and engagement of our target audience. These newsletters maintained regular contact with subscribers while keeping them informed about the latest brand updates and new developments in education and the French language.",
    newslettersFr:
      "Dans le cadre de ma stratégie de communication chez Educlever, j'ai conçu et géré plusieurs newsletters destinées à renforcer la visibilité de la marque et l'engagement de notre audience cible. Elles permettaient de maintenir un contact régulier avec les abonnés tout en les informant des dernières actualités de la marque et des évolutions dans les domaines de l'éducation et de la langue française.",
    newslettersImage: "assets/newsletters-showcase.jpg",
    newslettersChamrousseEn:
      "This project brings together several newsletter formats designed for different audiences and objectives: B2B and B2C communication for Chamrousse, alongside editorial content developed for Educlever within the Editis group.",
    newslettersChamrousseFr:
      "Ce projet rassemble plusieurs formats de newsletters conçus pour répondre à des publics et à des objectifs différents : communication B2B et B2C pour Chamrousse, ainsi que contenus éditoriaux développés pour Educlever au sein du groupe Editis.",
    newsletterB2BTitleEn: "Newsletter for resort professionals",
    newsletterB2BTitleFr: "Newsletter à destination des professionnels",
    newsletterB2BEn:
      "A monthly communication tool for local businesses, partners and resort professionals, bringing together events, operational news and useful resources for the season.",
    newsletterB2BFr:
      "Un outil de communication mensuel destiné aux acteurs économiques, partenaires et professionnels de la station, qui rassemble les événements, actualités opérationnelles et ressources utiles pour la saison.",
    newsletterB2BImage: "assets/B2B.png",
    newsletterB2CTitleEn: "Newsletter for visitors",
    newsletterB2CTitleFr: "Newsletter à destination du grand public",
    newsletterB2CEn:
      "A visitor-focused newsletter designed to inspire stays, highlight seasonal experiences and make the resort's activities and practical offers easy to discover.",
    newsletterB2CFr:
      "Une newsletter destinée aux visiteurs, conçue pour inspirer les séjours, valoriser les expériences de saison et faciliter la découverte des activités et offres pratiques de la station.",
    newsletterB2CImage: "assets/B2C.png",
    newsletterEditisTitleEn: "Educlever editorial newsletters",
    newsletterEditisTitleFr: "Newsletters éditoriales Educlever",
    newsletterEditisEn:
      "At Educlever, part of the Editis group, I designed and managed newsletters to maintain regular contact with subscribers, share brand news and highlight developments in education and the French language.",
    newsletterEditisFr:
      "Chez Educlever, au sein du groupe Editis, j'ai conçu et géré des newsletters afin de maintenir un contact régulier avec les abonnés, de partager les actualités de la marque et de valoriser les évolutions liées à l'éducation et à la langue française.",
    newsletterEditisImage: "assets/educlever-newsletter.png",
    newsletterEditisClicksValue: "> 60%",
    newsletterEditisClicksEn: "click-through rate",
    newsletterEditisClicksFr: "de taux de clics",
    whitePaperEn:
      "In addition to the university competitions I participated in over the past three years for clients such as Tefal, Ferrari, the International Ski School and Café Mokxa, I wrote and designed a white paper to conclude my Master's degree. Focused on festivals and the environment, it is primarily intended for festival organisers, as well as anyone curious about the topic.",
    whitePaperFr:
      "En complément des concours universitaires auxquels j'ai participé pendant trois ans pour des clients tels que Tefal, Ferrari, l'École de Ski Internationale et Café Mokxa, j'ai rédigé et conçu un livre blanc pour conclure mon Master. Consacré aux festivals et à l'environnement, il s'adresse principalement aux organisateurs de festivals, mais aussi à toute personne curieuse ou intéressée par le sujet.",
    chamrousseTabEn: "Chamrousse Tourist Office website modernisation",
    chamrousseTabFr: "Modernisation du site de l'Office de Tourisme de Chamrousse",
    chamrousseIntroTitleEn: "Page redesign and web content coordination",
    chamrousseIntroTitleFr: "Refonte de pages et coordination de contenus web",
    chamrousseIntroEn:
      "My role is to make the website more engaging, clearer and easier to use for visitors preparing their stay in Chamrousse. I work on page structure, visual hierarchy, multilingual clarity and content updates.",
    chamrousseIntroFr:
      "Mon rôle consiste à rendre le site plus engageant, plus clair et plus simple à utiliser pour les visiteurs qui préparent leur séjour à Chamrousse. Je travaille sur la structure des pages, la hiérarchie visuelle, la clarté multilingue et la mise à jour des contenus.",
    chamrousseTechEn:
      "I manage the website through the Ingénie back office and modernise pages by editing their HTML and CSS source code.",
    chamrousseTechFr:
      "J'administre le site depuis le back-office Ingénie et je modernise les pages en modifiant leur code source HTML et CSS.",
    chamrousseStatsEn: "+20% clicks, -25% bounce rate, with CTR monitored to improve calls-to-action and internal links.",
    chamrousseStatsFr: "+20 % de clics, -25 % de taux de rebond, avec un suivi du CTR pour améliorer les appels à l'action et les liens internes.",
    chamrousseClicksValue: "+20%",
    chamrousseClicksEn: "clicks on the redesigned page",
    chamrousseClicksFr: "de clics sur la page modernisée",
    chamrousseBounceValue: "-25%",
    chamrousseBounceEn: "bounce rate",
    chamrousseBounceFr: "de taux de rebond",
    chamrousseCtrValue: "CTR",
    chamrousseCtrEn: "monitored to optimise calls-to-action and internal links",
    chamrousseCtrFr: "suivi pour optimiser les appels à l'action et les liens internes",
    agoraWebsiteEn:
      "The Agora Portal, now renamed Le Coin Infos, was a page created by my Digital Communication department, in which I actively participated. I wrote content, contributed to the layout of various sections with the project manager and UX designer, and managed the page weekly to update articles, mutual insurance solutions and support programmes. I also handled the internal communication of the project through newsletters, social media and video-conference presentations.",
    agoraWebsiteFr:
      "Le Portail Agora, aujourd'hui renommé Le Coin Infos, est une page créée par mon service Communication digitale, à laquelle j'ai activement participé. J'ai rédigé des contenus, contribué à la mise en page de différentes sections avec le chef de projet et l'UX designer, puis administré la page chaque semaine afin de mettre à jour les articles, les solutions de mutuelle et les dispositifs d'accompagnement. J'ai également piloté la communication interne du projet à travers des newsletters, les réseaux sociaux et des présentations en visioconférence.",
    agoraWebsiteLink: "https://ensemble.aesio.fr/le-coin-infos",
    agoraWebsiteImage: "assets/aesio-coin-infos-preview.jpg",
    agoraTechEn: "This project was managed through the Drupal back office.",
    agoraTechFr: "Ce projet a été administré depuis le back-office Drupal.",
    agoraStatVisitsValue: "+68.9%",
    agoraStatVisitsEn: "visits compared with 2022",
    agoraStatVisitsFr: "de visites par rapport à 2022",
    agoraStatViewsValue: "+27.2%",
    agoraStatViewsEn: "page views compared with 2022",
    agoraStatViewsFr: "de pages vues par rapport à 2022",
    agoraStatMonthValue: "15.6k",
    agoraStatMonthEn: "visits and 1,719 journeys to the Business website in one month",
    agoraStatMonthFr: "visites et 1 719 passerelles vers le site Business en un mois",
    seoEn:
      "As part of this project, I was responsible for improving the SEO of the AÉSIO Mutuelle website. Over several months, I wrote articles and implemented internal linking between pages to create a new structure focused on prevention. This strategy aimed to position the website at the top of search engine results for prevention-related keywords.",
    seoFr:
      "Dans le cadre de ce projet, j'étais chargé d'améliorer le référencement naturel du site d'AÉSIO mutuelle. Pendant plusieurs mois, j'ai rédigé des articles et mis en place un maillage interne entre les pages afin de créer une nouvelle structure consacrée à la prévention. Cette stratégie visait à positionner le site parmi les premiers résultats des moteurs de recherche sur différents mots-clés liés à la prévention.",
    seoLink: "https://ensemble.aesio.fr/aesio-mag/prevention-sante-quels-enjeux",
    seoImage: "assets/aesio-seo-preview.jpg",
    seoTechEn: "The content and SEO structure were managed through the Drupal back office.",
    seoTechFr: "Les contenus et la structure SEO ont été administrés depuis le back-office Drupal.",
    seoStatSlowValue: "71 → 40",
    seoStatSlowEn: "slow URLs between April and August",
    seoStatSlowFr: "URL lentes entre avril et août",
    seoStatFastValue: "18 → 34",
    seoStatFastEn: "fast URLs between April and August",
    seoStatFastFr: "URL rapides entre avril et août",
    seoStatPositionValue: "#3",
    seoStatPositionEn: "position reached by the “Vivre mieux” content silo",
    seoStatPositionFr: "position atteinte par le silo « Vivre mieux »",
  },
  contactTitle: "On échange ?",
  contactText: "Je suis disponible pour discuter d'une opportunité, d'un entretien ou d'un projet.",
  email: "joffrey.achard@email.com",
  phone: "+33 7 83 71 61 89",
  linkedin: "https://www.linkedin.com/",
  colors: {
    bg: "#f5f1e8",
    ink: "#17201b",
    accent: "#0f6b5d",
    accentStrong: "#09473f",
    warm: "#d66f55",
  },
  layoutVersion: 2,
  layoutSections: [
    { id: "projects", label: "Projects", visible: true },
    { id: "cv", label: "CV and skills", visible: true },
    { id: "portrait", label: "Profile", visible: true },
    { id: "traits", label: "Key traits", visible: true },
    { id: "approach", label: "How I work", visible: true },
    { id: "contact", label: "Contact", visible: true },
  ],
  pillars: [
    {
      title: "Exploration",
      text: "Mobilité internationale, voyages, rencontres et curiosité pour les environnements nouveaux.",
    },
    {
      title: "Méthode",
      text: "Une envie de rêver grand, mais avec des budgets, des plans et une exécution concrète.",
    },
    {
      title: "Persistance",
      text: "Apprendre, progresser et tenir le cap même quand le chemin demande de la patience.",
    },
  ],
  traits: [
    "Curiosité intellectuelle",
    "Adaptabilité",
    "Communication digitale",
    "Ouverture interculturelle",
    "Gestion de projet",
  ],
  skills: [
    "Marketing digital et communication",
    "Création de contenu, vidéo et réseaux sociaux",
    "Gestion de projet et coordination",
    "Analyse, synthèse et présentation",
    "Anglais professionnel et mobilité internationale",
  ],
  projects: [
    {
      title: "Web Project Management",
      type: "Office de Tourisme de Chamrousse",
      text: "Depuis mars 2026, je suis responsable du site web de l'Office de Tourisme de Chamrousse et je travaille à rendre ses pages plus claires, plus visuelles et plus efficaces.",
      link: "#",
      color: "#315f72",
      image: "assets/chamrousse-cover.jpg",
    },
    {
      title: "Rédaction & Journalisme",
      type: "Média musical électronique Valliue",
      text: "Depuis août 2021, je rédige et mets en page des articles, les valorise sur les réseaux sociaux et négocie des partenariats avec des événements musicaux.",
      link: "https://valliue.com/author/jooffrey/",
      color: "#0f6b5d",
      image: "assets/valliue-photo-cover.jpg",
    },
    {
      title: "Vidéos",
      type: "Motion design et reportage",
      text: "Production de vidéos pour BASSETTI Group et Educlever, du brief initial jusqu'à la diffusion.",
      link: "#",
      color: "#315f72",
      image: "assets/videos-project-cover.jpg",
    },
    {
      title: "Documents de communication",
      type: "Supports marketing",
      text: "Création de supports pour BASSETTI Group et l'équipe commerciale d'Educlever.",
      link: "#",
      color: "#7b5842",
      image: "assets/communication-documents-cover.svg",
    },
    {
      title: "Plan de communication",
      type: "Stratégie LinkedIn et planning éditorial",
      text: "Plans de communication destinés à renforcer la notoriété d'Orthodidacte sur LinkedIn.",
      link: "#",
      color: "#c9973f",
      image: "assets/communication-plan-cover.svg",
    },
    {
      title: "Newsletters",
      type: "Engagement de l'audience",
      text: "Conception et gestion de newsletters pour Educlever.",
      link: "#",
      color: "#0f6b5d",
      image: "assets/newsletters-cover.svg",
    },
    {
      title: "Livre blanc",
      type: "Recherche et design éditorial",
      text: "Rédaction et mise en page d'un livre blanc sur l'empreinte carbone des festivals.",
      link: "assets/livre-blanc-festivals.pdf",
      color: "#6c6f3f",
      image: "assets/white-paper-cover.svg",
    },
    {
      title: "Création de brief",
      type: "Direction créative et motion design",
      text: "Création de briefs et organisation de vidéos pour le Portail Agora / Le Coin Infos.",
      link: "https://www.youtube.com/watch?v=8AQAjC1kFic&list=PLaxJVgkhTIUxC_CiFGCUwFuZlrdWHYQ6K",
      color: "#d66f55",
      image: "assets/brief-cover.svg",
    },
  ],
  i18n: {
    en: {
      metaDescription:
        "Joffrey Achard's portfolio: projects, presentation video, experience, CV and contact.",
      navProjects: "Projects",
      navVideo: "Video",
      navCv: "CV",
      navContact: "Contact",
      adminLabel: "Admin",
      primaryCta: "View my projects",
      secondaryCta: "Download my resume",
      videoLabel: "Presentation",
      profileLabel: "Profile",
      traitsLabel: "Key traits",
      approachLabel: "How I work",
      approachTitle: "How I turn an idea into something real.",
      projectsLabel: "Selected work",
      projectsTitle: "Projects",
      portfolioCta: "Open PDF portfolio",
      cvLabel: "Experience",
      strengthsTitle: "Core strengths",
      contactLabel: "Contact",
      emailCta: "Send me an email",
      phoneCta: "Phone",
      linkedinCta: "LinkedIn",
      topLink: "Back to top",
      footerText: "Personal portfolio.",
      projectLink: "View project",
      closeProject: "Close project",
      beforeLabel: "Before",
      afterLabel: "After",
      articlesLabel: "Articles",
      collaborationsLabel: "Collaborations",
      statisticsLabel: "Statistics",
      openLinkLabel: "Open link",
      eyebrow: "Welcome to my portfolio",
      headline: "Hi, I'm Joffrey! Explore my portfolio and the projects behind my journey.",
      intro:
        "My name is Joffrey Achard and I work in digital marketing and communication.\n\nAfter several professional experiences in France, a semester studying in the United Kingdom, and several months travelling and volunteering across North and South America, I developed a strong desire to build my career in an international environment.\n\nWhat interests me most is discovering new ways of working, collaborating with multicultural teams and taking on challenges in different contexts. For me, marketing is a way to connect people, tell stories and help projects gain visibility, wherever in the world they come to life.\n\nThrough this portfolio, I share my journey, my work and the experiences that have shaped my view of the world and my profession.",
      profileTitle: "A curious mind, open to the world.",
      profileText:
        "I enjoy discovering new environments, understanding different ways of thinking and regularly stepping outside my comfort zone. Part of me wants to explore, experiment and imagine what could come next. Another part needs to build, organise and see things through. Today, I am looking above all for projects that allow me to learn, collaborate with people from different backgrounds and continue to grow, both professionally and personally.",
      videoTitle: "My presentation video",
      videoNote:
        "I am currently editing this video. It will be a more personal way to introduce myself, explain where I come from and share what I would like to build next.",
      cvTitle: "CV and skills",
      cvText:
        "Master's degree in Marketing and Communication, four years of experience, international exposure, and hands-on expertise in content, web projects, analytics and digital communication.",
      contactTitle: "Let's talk",
      contactText: "I am available to discuss an international opportunity, an interview or a collaboration.",
      pillars: [
        {
          title: "Exploration",
          text: "New places and unfamiliar environments give me energy. They push me to listen, adapt and see things from another point of view.",
        },
        {
          title: "Method",
          text: "I enjoy ambitious ideas, but I also need to make them workable. I ask questions, organise the information and move forward step by step.",
        },
        {
          title: "Persistence",
          text: "I can question myself along the way, but I do not give up easily. I learn, adjust and keep going until the work feels right.",
        },
      ],
      traits: [
        "Intellectual curiosity",
        "Adaptability",
        "Digital communication",
        "Intercultural openness",
        "Project management",
      ],
      skills: [
        "Digital communication and analytics (GA4)",
        "Web project management: WordPress, Drupal and SEO updates",
        "Copywriting, storytelling and content strategy",
        "Marketing campaign management",
        "Adobe Suite, Canva, MS Suite and video editing tools",
      ],
      projects: [
        {
          title: "Web Project Management",
          type: "Chamrousse Tourist Office",
          text: "Since March 2026, I have been responsible for Chamrousse Tourist Office's website, improving its visual appeal and making communication clearer for French, English and German-speaking visitors.",
          link: "#",
          color: "#315f72",
          image: "assets/chamrousse-cover.jpg",
          detailTitle: "Website redesign and content coordination",
          detailText:
            "My role focuses on making the website more engaging, clearer and easier to use for visitors preparing their stay in Chamrousse. I work on page structure, visual hierarchy, multilingual clarity and content updates.",
          beforeAfter: {
            before: "Before: dense pages, less visual rhythm and information that was harder to scan.",
            after: "After: clearer sections, stronger visuals and a more direct path to useful information.",
          },
          detailBullets: [
            "Website content management and page updates",
            "Visual improvements to make key pages more attractive",
            "Clearer communication for FR / EN / DE audiences",
            "UX-oriented thinking to support visitor information and commercial goals",
          ],
        },
        {
          title: "Writing & Journalism",
          type: "Valliue electronic music media",
          text: "Since 2021, I have written and formatted articles for Valliue, promoted them on social media and negotiated collaborations with major electronic music festivals.",
          link: "https://valliue.com/author/jooffrey/",
          color: "#0f6b5d",
          image: "assets/valliue-photo-cover.jpg",
          detailTitle: "Electronic music media, articles and partnerships",
          detailText:
            "For Valliue, I write articles under the name Jooffrey, cover events, interview artists and contribute to partnerships with festivals and cultural organisations.",
          articles: [
            "News articles, new music releases and album coverage",
            "Event reports from festivals and concerts",
            "Artist interviews, including international interviews",
            "All published articles are available on my Valliue author page",
          ],
          collaborations: [
            "Lollapalooza Paris",
            "Delta Festival",
            "Sea You Festival",
            "Dream Nation Festival",
            "Pharaonic Festival",
            "Dystopia Festival",
            "Audiogenic",
            "FCKNYE Festival",
            "Siks",
          ],
          stats: [
            "Published articles: to be completed",
            "Traffic contribution: to be completed",
            "Festival partnerships: to be completed",
          ],
        },
        {
          title: "Video production",
          type: "Motion design and reporting",
          text: "For BASSETTI Group and Educlever, I managed video projects from the initial brief and production through to online distribution and promotion.",
          link: "#",
          color: "#315f72",
          image: "assets/videos-project-cover.jpg",
        },
        {
          title: "Communication documents",
          type: "Marketing materials",
          text: "I created and updated product sheets, white papers, landing pages, banners, flyers, webinar materials and B2B brochures for sales and marketing teams.",
          link: "#",
          color: "#7b5842",
          image: "assets/communication-documents-cover.svg",
        },
        {
          title: "Communication plan",
          type: "LinkedIn strategy and editorial planning",
          text: "At Educlever, I developed communication plans to strengthen Orthodidacte's brand awareness on LinkedIn.",
          link: "#",
          color: "#c9973f",
          image: "assets/communication-plan-cover.svg",
        },
        {
          title: "Newsletters",
          type: "Audience engagement and brand updates",
          text: "At Educlever, I designed and managed newsletters to maintain regular contact with subscribers and strengthen engagement.",
          link: "#",
          color: "#0f6b5d",
          image: "assets/newsletters-cover.svg",
        },
        {
          title: "White paper",
          type: "Research and editorial design",
          text: "As part of my Master's degree, I wrote and designed a white paper on reducing the carbon footprint of music festivals.",
          link: "assets/livre-blanc-festivals.pdf",
          color: "#6c6f3f",
          image: "assets/white-paper-cover.svg",
        },
        {
          title: "Creative brief writing",
          type: "Creative direction and motion design",
          text: "For the Agora Portal / Le Coin Infos motion design videos, I created the briefs, captured website content and organised the video structure to support production.",
          link: "https://www.youtube.com/watch?v=8AQAjC1kFic&list=PLaxJVgkhTIUxC_CiFGCUwFuZlrdWHYQ6K",
          color: "#d66f55",
          image: "assets/brief-cover.svg",
        },
      ],
    },
    fr: {
      metaDescription:
        "Portfolio de Joffrey Achard : projets, vidéo de présentation, parcours, CV et contact.",
      navProjects: "Projets",
      navVideo: "Vidéo",
      navCv: "CV",
      navContact: "Contact",
      adminLabel: "Admin",
      primaryCta: "Voir mes projets",
      secondaryCta: "Télécharger mon CV",
      videoLabel: "Présentation",
      profileLabel: "Portrait",
      traitsLabel: "Traits distinctifs",
      approachLabel: "Manière de travailler",
      approachTitle: "Comment je transforme une idée en projet concret.",
      projectsLabel: "Sélection",
      projectsTitle: "Projets",
      portfolioCta: "Ouvrir le portfolio PDF",
      cvLabel: "Parcours",
      strengthsTitle: "Points forts",
      contactLabel: "Contact",
      emailCta: "M'envoyer un email",
      phoneCta: "Téléphone",
      linkedinCta: "LinkedIn",
      topLink: "Retour en haut",
      footerText: "Portfolio personnel.",
      projectLink: "Voir le projet",
      closeProject: "Fermer le projet",
      beforeLabel: "Avant",
      afterLabel: "Après",
      articlesLabel: "Articles",
      collaborationsLabel: "Collaborations",
      statisticsLabel: "Statistiques",
      openLinkLabel: "Ouvrir le lien",
      eyebrow: "Bienvenue sur mon portfolio",
      headline: "Bonjour, moi c'est Joffrey ! Découvrez mon portfolio et les projets qui ont façonné mon parcours.",
      intro:
        "Je m'appelle Joffrey Achard et je travaille dans le marketing digital et la communication.\n\nAprès plusieurs expériences en France, un semestre d'études au Royaume-Uni et plusieurs mois de voyage et de volontariat à travers l'Amérique du Nord et l'Amérique du Sud, j'ai développé une forte envie d'évoluer dans un environnement international.\n\nCe qui m'intéresse avant tout, c'est découvrir de nouvelles façons de travailler, collaborer avec des équipes multiculturelles et relever des défis dans des contextes différents. Le marketing est pour moi un moyen de créer du lien, raconter des histoires et faire rayonner des projets, quel que soit le pays où ils prennent vie.\n\nÀ travers ce portfolio, je partage mon parcours, mes réalisations et les expériences qui ont contribué à construire ma vision du monde et de mon métier.",
      profileTitle: "Un esprit curieux, tourné vers le monde.",
      profileText:
        "J'aime découvrir de nouveaux environnements, comprendre différentes façons de penser et sortir régulièrement de ma zone de confort. Une partie de moi a envie d'explorer, d'essayer et d'imaginer la suite. L'autre a besoin de construire, d'organiser et d'aller au bout des choses. Aujourd'hui, je cherche avant tout des projets qui me permettent d'apprendre, de collaborer avec des personnes venues d'horizons différents et de continuer à grandir, professionnellement comme personnellement.",
      videoTitle: "Ma vidéo de présentation",
      videoNote:
        "Je travaille encore sur le montage de cette vidéo. Elle me permettra de me présenter de façon plus personnelle, de raconter mon parcours et d'expliquer ce que j'aimerais construire ensuite.",
      cvTitle: "CV et compétences",
      cvText:
        "Master en Marketing et Communication, quatre ans d'expérience, une ouverture internationale et des compétences concrètes en contenu, projets web, analytics et communication digitale.",
      contactTitle: "On échange ?",
      contactText: "Je suis disponible pour discuter d'une opportunité internationale, d'un entretien ou d'une collaboration.",
      pillars: [
        {
          title: "Exploration",
          text: "Les nouveaux lieux et les environnements inconnus me donnent de l'énergie. Ils m'obligent à écouter, à m'adapter et à changer de point de vue.",
        },
        {
          title: "Méthode",
          text: "J'aime les idées ambitieuses, mais j'ai aussi besoin de les rendre réalisables. Je pose des questions, j'organise les informations et j'avance étape par étape.",
        },
        {
          title: "Persistance",
          text: "Il m'arrive de douter en cours de route, mais je n'abandonne pas facilement. J'apprends, j'ajuste et je continue jusqu'à ce que le résultat me semble juste.",
        },
      ],
      traits: [
        "Curiosité intellectuelle",
        "Adaptabilité",
        "Communication digitale",
        "Ouverture interculturelle",
        "Gestion de projet",
      ],
      skills: [
        "Communication digitale et analytics (GA4)",
        "Gestion de projets web : WordPress, Drupal et mises à jour SEO",
        "Copywriting, storytelling et stratégie de contenu",
        "Gestion de campagnes marketing",
        "Suite Adobe, Canva, Suite MS et outils de montage vidéo",
      ],
      projects: [
        {
          title: "Web Project Management",
          type: "Office de Tourisme de Chamrousse",
          text: "Depuis mars 2026, je suis responsable du site web de l'Office de Tourisme de Chamrousse. J'ai dynamisé le site pour le rendre plus attractif visuellement et clarifier la communication auprès des clients FR / EN / DE.",
          link: "#",
          color: "#315f72",
          image: "assets/chamrousse-cover.jpg",
          detailTitle: "Refonte de pages et coordination de contenus web",
          detailText:
            "Mon rôle consiste à rendre le site plus engageant, plus clair et plus simple à utiliser pour les visiteurs qui préparent leur séjour à Chamrousse. Je travaille sur la structure des pages, la hiérarchie visuelle, la clarté multilingue et la mise à jour des contenus.",
          beforeAfter: {
            before: "Avant : des pages denses, moins rythmées visuellement et plus difficiles à parcourir rapidement.",
            after: "Après : des sections plus claires, des visuels plus présents et un accès plus direct aux informations utiles.",
          },
          detailBullets: [
            "Gestion des contenus et mises à jour du site",
            "Amélioration visuelle de pages stratégiques",
            "Communication plus claire pour les audiences FR / EN / ALL",
            "Réflexion UX pour soutenir l'information des visiteurs et les objectifs commerciaux",
          ],
        },
        {
          title: "Rédaction & Journalisme",
          type: "Média musical électronique Valliue",
          text: "Depuis 2021, je rédige et mets en page des articles pour Valliue, les valorise sur les réseaux sociaux et négocie des collaborations avec de grands festivals de musique électronique.",
          link: "https://valliue.com/author/jooffrey/",
          color: "#0f6b5d",
          image: "assets/valliue-photo-cover.jpg",
          detailTitle: "Média consacré à la musique électronique, articles et partenariats",
          detailText:
            "Pour Valliue, je rédige des articles sous le nom Jooffrey, couvre des événements, interviewe des artistes et participe aux partenariats avec des festivals et des structures culturelles.",
          articles: [
            "Articles d'actualité, nouvelles sorties musicales et albums",
            "Reportages d'événements, festivals et concerts",
            "Interviews d'artistes, dont des interviews internationales",
            "Tous mes articles publiés sont disponibles sur ma page auteur Valliue",
          ],
          collaborations: [
            "Lollapalooza Paris",
            "Delta Festival",
            "Sea You Festival",
            "Dream Nation Festival",
            "Pharaonic Festival",
            "Dystopia Festival",
            "Audiogenic",
            "FCKNYE Festival",
            "Siks",
          ],
          stats: [
            "Articles publiés : à compléter",
            "Contribution au trafic : à compléter",
            "Partenariats avec des festivals : à compléter",
          ],
        },
        {
          title: "Production vidéo",
          type: "Motion design et reportage",
          text: "Pour BASSETTI Group et Educlever, j'ai piloté des projets vidéo du brief initial et de la production jusqu'à leur diffusion et leur promotion en ligne.",
          link: "#",
          color: "#315f72",
          image: "assets/videos-project-cover.jpg",
        },
        {
          title: "Documents de communication",
          type: "Supports marketing",
          text: "J'ai créé et mis à jour des fiches produits, livres blancs, landing pages, bannières, flyers, supports de webinaire et livrets BtoB pour les équipes commerciales et marketing.",
          link: "#",
          color: "#7b5842",
          image: "assets/communication-documents-cover.svg",
        },
        {
          title: "Plan de communication",
          type: "Stratégie LinkedIn et planning éditorial",
          text: "Chez Educlever, j'ai élaboré des plans de communication afin de renforcer la notoriété d'Orthodidacte sur LinkedIn.",
          link: "#",
          color: "#c9973f",
          image: "assets/communication-plan-cover.svg",
        },
        {
          title: "Newsletters",
          type: "Engagement de l'audience et actualités de marque",
          text: "Chez Educlever, j'ai conçu et géré des newsletters afin de maintenir un contact régulier avec les abonnés et de renforcer leur engagement.",
          link: "#",
          color: "#0f6b5d",
          image: "assets/newsletters-cover.svg",
        },
        {
          title: "Livre blanc",
          type: "Recherche et design éditorial",
          text: "Dans le cadre de mon Master, j'ai rédigé et mis en page un livre blanc sur la réduction de l'empreinte carbone des festivals de musique.",
          link: "assets/livre-blanc-festivals.pdf",
          color: "#6c6f3f",
          image: "assets/white-paper-cover.svg",
        },
        {
          title: "Création de brief",
          type: "Direction créative et motion design",
          text: "Pour les vidéos en motion design du Portail Agora / Le Coin Infos, j'ai créé les briefs, capturé les contenus du site et organisé la structure des vidéos afin d'accompagner leur production.",
          link: "https://www.youtube.com/watch?v=8AQAjC1kFic&list=PLaxJVgkhTIUxC_CiFGCUwFuZlrdWHYQ6K",
          color: "#d66f55",
          image: "assets/brief-cover.svg",
        },
      ],
    },
  },
};
